### ISSUE TITLE
Interest in accessing secrets via API instead of CLI?

### ISSUE THREAD

**Issue by geoffharcourt** [muhlba91/doppler-secrets-buildkite-plugin#8]
Hello, thanks for creating the plugin!

We're looking at transitioning our CI secrets to Doppler. Would you be open to a PR to use the API instead of the CLI? (Using the API would enable agents such as the default Elastic CI stack agents that don't have the Doppler CLI installed to use secrets.)

**Comment by muhlba91** [comment]
Hi,

thank you for your interest to contribute!

Yes, sure. Please go ahead with a PR. I actually believe using the API rather than the CLI creates a lot of value. 😃
